StudentWebs/Controllers/StudentsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentWebs.Data;
using StudentWebs.Models;
using Microsoft.AspNetCore.Hosting;

namespace StudentWebs.Controllers
{
    public class StudentsController : Controller
    {
        private readonly DataContext _context;
        private readonly IWebHostEnvironment _environment;

        public StudentsController(DataContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Students.Include(s => s.Faculty);
            return View(await dataContext.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.Faculty)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Student student)
        {
            DateTime eighteenYearsAgo = DateTime.Today.AddYears(-18);
            if (student.DateOfBirth.Date > eighteenYearsAgo || student.DateOfBirth.Date >= DateTime.Today.AddDays(1))
            {
                ModelState.AddModelError("DateOfBirth", "Date of birth Error!. Please Enter valid DOB");
            }
            bool isSymbolNoExists = _context.Students.Any(s => s.SymbolNo == student.SymbolNo);
            if (isSymbolNoExists)
            {
                ModelState.AddModelError("SymbolNo", "Symbol No already exists.");
            }
            if (ModelState.IsValid)
            {
                if (student != null)
                {
                    string uniqueFileName = UploadedFile(student);
                    student.ImagePath = uniqueFileName;
                }

                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName", student.FacultyId);
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName", student.FacultyId);
            return View(student);
        }

        // POST: Students/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Student student)
        {
            if (id != student.StudentId)
            {
                return NotFound();
            }
            if (student.DateOfBirth.Date > DateTime.Today)
            {
                ModelState.AddModelError("DateOfBirth", "Date of birth Error!.Please Enter Valid DOB");
            }

            var result = await _context.Students.FirstOrDefaultAsync(x => x.StudentId == student.StudentId);
            if(result.SymbolNo != student.SymbolNo)
            {
                bool isSymbolNoExists = _context.Students.Any(s => s.SymbolNo == student.SymbolNo);
                if (isSymbolNoExists)
                {
                    ModelState.AddModelError("SymbolNo", "Symbol No already exists.");
                }
            }
            if (student.Image == null)
            {

                student.ImagePath = result.ImagePath;

            }

            if (ModelState.IsValid)
            {
                if (student.Image != null)
                {
                    if (student != null)
                    {
                        string uniqueFileName = UploadedFile(student);
                        student.ImagePath = uniqueFileName;
                    }
                }
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName", student.FacultyId);
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.Faculty)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'DataContext.Students'  is null.");
            }
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool StudentExists(int id)
        {
          return (_context.Students?.Any(e => e.StudentId == id)).GetValueOrDefault();
        }
       public string UploadedFile(Student student)
        {
            string uniqueFileName = null;
            if(student.Image != null)
            {
                var uploadsFolder = Path.Combine(_environment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + student.Image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    student.Image.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

StudentWebs/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using StudentWebs.Data;
using StudentWebs.Models;

namespace StudentWebs.Controllers
{
    public class TeachersController : Controller
    {
        private readonly DataContext _context;
        private readonly IWebHostEnvironment _environment;

        public TeachersController(DataContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        
        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Teachers.Include(t => t.Faculty);
            return View(await dataContext.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Teachers == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .Include(t => t.Faculty)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Teacher teacher)
        {
            bool isHodExist = _context.Teachers.Any(s => s.FacultyId == teacher.FacultyId);

            if (isHodExist)
            {
                ModelState.AddModelError("FacultyId", "HOD of this faculty already exists.");
            }

            if (ModelState.IsValid)
            {

                if (teacher != null)
                {
                    string uniqueFileName = UploadedFile(teacher);
                   teacher.ImagePath = uniqueFileName;
                }
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName", teacher.FacultyId);
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Teachers == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName", teacher.FacultyId);
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Teacher teacher)
        {

            if (id != teacher.Id)
            {
                return NotFound();
            }
            var result = await _context.Teachers.FirstOrDefaultAsync(x => x.Id == teacher.Id);
            if (result.FacultyId != teacher.FacultyId)
            {
                bool isHodExist = _context.Teachers.Any(s => s.FacultyId == teacher.FacultyId);

                if (isHodExist)
                {
                    ModelState.AddModelError("FacultyId", "HOD of this faculty already exists.");
                }
            }
            if (teacher.Image == null)
            {

                teacher.ImagePath = result.ImagePath;

            }
            

            if (ModelState.IsValid)
            {
                if (teacher.Image != null)
                {
                    if (teacher != null)
                    {
                        string uniqueFileName = UploadedFile(teacher);
                        teacher.ImagePath = uniqueFileName;
                    }
                }
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyId"] = new SelectList(_context.Facultys, "Id", "FacultyName", teacher.FacultyId);
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Teachers == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .Include(t => t.Faculty)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Teachers == null)
            {
                return Problem("Entity set 'DataContext.Teachers'  is null.");
            }
            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher != null)
            {
                _context.Teachers.Remove(teacher);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
          return (_context.Teachers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public string UploadedFile(Teacher teacher)
        {
            string uniqueFileName = null;
            if (teacher.Image != null)
            {
                var uploadsFolder = Path.Combine(_environment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + teacher.Image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    teacher.Image.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

StudentWebs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentWebs</title>
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentWebs.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Student MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    @*    <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Faculties" asp-action="Index">Faculties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Fee" asp-action="Index">Fees</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="StudentDetails" asp-action="Index">Student Details</a>
                        </li>*@
                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
                @if(User.Identity.IsAuthenticated)
                {
                    <div class="navbar float-end">
                        <span class="userSession">Welcome @User.Identity.Name</span>
                        <div class="btn-group">
                        <a class="btn btn-sm btn-danger" asp-action="LogOut" asp-controller="Account">SignOut</a>
                        </div>
                        </div>
                }
            </div>
        </nav>
    </header>
 
        
            @RenderBody()
       
  

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 - StudentWebs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudentWebs/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentWeb</title>
    <link rel="stylesheet" href="~/css/bootwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>